site_name: Céu-Arduino v0.20 - Reference Manual
theme:     readthedocs
#site_dir:  site/v0.20

pages:
- Home:            index.md
- Introduction:    010-introduction.md
- Modes:           020-modes.md
- Pins:            030-pins.md
- License:         license.md

