site_name: Céu-Arduino v0.20 - Reference Manual
theme:     readthedocs
#site_dir:  site/v0.20

pages:
- Home:                 index.md
- Introduction:         010-introduction.md
- Modes of Operation:   020-modes.md
- Digital Pins:         030-pins.md
- Serial Communication: 040-serial.md
- License:              license.md

